### ISSUE TITLE
Plugin page bug makes it impossible to use

### ISSUE THREAD

**Issue by mrgame64** [NodeBB/nodebb-plugin-category-sections#1]
This happens upon pressing the "New Section" button
<img width="1438" alt="screen shot 2015-07-30 at 02 44 19" src="https://cloud.githubusercontent.com/assets/5879873/8981491/28984d7a-36b9-11e5-9d4f-63c371d90d67.png">

The plugin page repeats itself within the left box like an infinite mirror every time the "New Section" button is pressed

**Comment by mrgame64** [comment]
It's the first and only issue in this repository, I'd really appreciate if it was given any attention

**Comment by ShogunPanda** [comment]
I fixed the issue in my fork. Basically just some forgotten refactoring I guess.
Hope this helps.

**Comment by mrgame64** [comment]
@ShogunPanda Thanks, I'll make sure to test it ASAP!

**Comment by IrealiTY** [comment]
I just installed a fresh version of nodebb and this plugin and I have the exact same issue.
NodeBB v0.7.3

nodebb-plugin-category-sections
Installed 0.1.5 | Latest 0.1.5

**Comment by mrgame64** [comment]
Using @ShogunPanda's fork seems to solve it, it would be nice if @psychobunny merged it

**Comment by eugenioclrc** [comment]
same issue here.. :(

**Comment by psychobunny** [comment]
thanks @ShogunPanda

**Comment by mrgame64** [comment]
A `npm publish` would be much appreciated ;)
