### ISSUE TITLE
NodeBB 1.5.0 + persona theme compatibility

### ISSUE THREAD

**Issue by Couby** [NodeBB/nodebb-plugin-category-sections#11]
Hi,

Any chance there could be an udpate for this plugin ? :blush:

Regards.

**Comment by dnkls** [comment]
I wish i can install it on my persona to

**Comment by dnkls** [comment]
some one use it http://i.imgur.com/0PRRV6m.png but how?

**Comment by juan-g** [comment]
That site uses CSS for category sections. See: https://community.nodebb.org/topic/8711/how-to-make-category-sections/10
