### ISSUE TITLE
Empty home page

### ISSUE THREAD

**Issue by mrgame64** [NodeBB/nodebb-plugin-category-sections#3]
In my NodeBB instance I have set the Categories page as my home page, yet as long as this plugin is left activated, no categories are visible, and I'm left with something like this:

<img width="164" alt="screen shot 2015-08-27 at 15 07 25" src="https://cloud.githubusercontent.com/assets/5879873/9521157/5e24235e-4ccd-11e5-94fe-9227f874d5da.png">

When I open the "Categories" route manually, though, it appears normal, but still the category sections aren't applied.

**Comment by eugenioclrc** [comment]
What theme are you using?
have you already create the sections and added categories to the sections and then press the green save button?

**Comment by mrgame64** [comment]
I'm using the latest Persona theme, and yes, I have created and saved the sections.

**Comment by mrgame64** [comment]
Even after the latest update to v0.1.7 and using NodeBB v0.8.1 the problem still persists.

**Comment by ghost** [comment]
I'm having the same problem. Has a solution or a cause been found?

**Comment by ASCIIcat** [comment]
I am having this same issue on NodeBB v1.0.3 with the Lavender theme 3.0.9

**Comment by gnimmelf** [comment]
Same here. It was working, but then suddenly empty after i fooled around with other plugins, so maybe som incompability. Perhaps styling, as I see no errors....

**Comment by maidoesthings** [comment]
This isn't working for me and I'm getting this error in my console when I'm trying to access the plugin in the ACP:
`Uncaught TypeError: $(...).sortable is not a function`
