### ISSUE TITLE
Is this compatible with NodeBB v0.8.2 ? When installed it breaks the forum. getting error "502 bad gateway nginx/1.8.0". After disabling things are back normal. Msg log at nodebb start is given below.

### ISSUE THREAD

**Issue by ngsankar** [NodeBB/nodebb-plugin-category-sections#5]
node app
22/9 01:40 [1272] - info: NodeBB vundefined Copyright (C) 2013-2014 NodeBB Inc.
22/9 01:40 [1272] - info: This program comes with ABSOLUTELY NO WARRANTY.
22/9 01:40 [1272] - info: This is free software, and you are welcome to redistri                                                                                        bute it under certain conditions.
22/9 01:40 [1272] - info:
22/9 01:40 [1272] - info: Time: Tue Sep 22 2015 01:40:20 GMT-0400 (EDT)
22/9 01:40 [1272] - info: Initializing NodeBB v0.8.2
22/9 01:40 [1272] - warn: [plugins/nodebb-plugin-sso-google-confirmed] Hook `fil                                                                                        ter:user.delete` is deprecated, please use an alternative
22/9 01:40 [1272] - warn: [plugins/nodebb-plugin-sso-facebook] Hook `filter:user                                                                                        .delete` is deprecated, please use an alternative

22/9 01:40 [1272] - warn: [plugins/load] The following plugins may not be compat                                                                                        ible with your version of NodeBB. This may cause unintended behaviour or crashin                                                                                        g. In the event of an unresponsive NodeBB caused by this plugin, run `./nodebb r                                                                                        eset -p PLUGINNAME` to disable it.
- nodebb-plugin-google-adsense
- nodebb-plugin-category-sectionst

22/9 01:40 [1272] - error: [plugins/emailer-mailgun] API key or Domain not set!
22/9 01:40 [1272] - info: NodeBB Ready
22/9 01:40 [1272] - info: Enabling 'trust proxy'
22/9 01:40 [1272] - info: NodeBB is now listening on: 0.0.0.0:4567

22/9 01:42 [1272] - error: SyntaxError: Unexpected token o
    at Object.parse (native)
    at /home/ngsankar/mynodebb/node_modules/nodebb-plugin-category-sections/library.js:71:53
    at try_callback (/home/ngsankar/mynodebb/node_modules/redis/index.js:573:9)
    at RedisClient.return_reply (/home/ngsankar/mynodebb/node_modules/redis/index.js:661:13)
    at ReplyParser.<anonymous> (/home/ngsankar/mynodebb/node_modules/redis/index.js:309:14)
    at ReplyParser.emit (events.js:95:17)
    at ReplyParser.send_reply (/home/ngsankar/mynodebb/node_modules/redis/lib/parser/javascript.js:300:10)
    at ReplyParser.execute (/home/ngsankar/mynodebb/node_modules/redis/lib/parser/javascript.js:203:22)
    at RedisClient.on_data (/home/ngsankar/mynodebb/node_modules/redis/index.js:534:27)
    at Socket.<anonymous> (/home/ngsankar/mynodebb/node_modules/redis/index.js:91:14)

**Comment by neutrino84** [comment]
I need this plugin, getting this too -- not sure if I should fix this or wait

**Comment by neutrino84** [comment]
issue fixed if anyone needs this plugin with 0.8.x https://github.com/neutrino84/nodebb-plugin-category-sections

**Comment by ArcticRaz0r** [comment]
@neutrino84 It's nice to see someone is still trying to maintain it :)
Is your fork compatible with v0.9.x as well?

**Comment by Nisthar** [comment]
@ArcticRaz0r I too want to know that
