### ISSUE TITLE
homepage is empty, even after uninstalling plugin.

### ISSUE THREAD

**Issue by ViolentCrumble** [NodeBB/nodebb-plugin-category-sections#9]
Hi this doesn't work, all it has done is removed my homepage, i created categories and dragged them in and pressed the green save button. nothing.

now i uninstalled it and my homepage is still empty, i have reset it back to categories. and set it to other things and then set it back and still empty?

what can i do?

**Comment by mrgame64** [comment]
I’ve always had this problem too, it never really worked, despite having appealed to the developers various times

**Comment by ViolentCrumble** [comment]
Managed to fix it, by removing the directory via console, then reloading and restarting the forum. some reason just restarting wasn't enough.

Edit: well not fix, rather repair the damage this plugin caused.

**Comment by jiangcaiyang** [comment]
Mine is the same, by reloading the forum, the problem resolved. Note, you could NOT reload the forum in ACP when installed this plugin.

**Comment by loversama** [comment]
Plugin still broke ^______^

**Comment by mrgame64** [comment]
Has it ever worked?
